pipeline {
    agent any

    stages {
        stage('Helm Changes') {
            when {
                changeset "helm/**"
            }

            stages {
                stage('Lint') {
                    steps {
                        echo 'Running helm lint'
                    }
                }

                stage('Test') {
                    steps {
                        echo 'Running helm template tests'
                    }
                }

                stage('Package') {
                    steps {
                        echo 'Packaging helm chart'
                    }
                }

                stage('Publish') {
                    steps {
                        echo 'Publishing to helm repository'
                    }
                }

                stage('Deploy to Dev') {
                    steps {
                        echo 'Deploying to development environment'
                    }
                }
            }
        }

        // Other non-helm related stages can go here
        stage('Cleanup') {
            steps {
                echo 'Cleaning up workspace'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
