pipeline {
    agent any

    when {
        changeset "helm/**"
    }

    stages {
        stage('Test Changeset') {
            parallel {
                stage('Step 1') {
                    steps {
                        echo 'Step 1'
                    }
                }

                stage('Step 2') {
                    steps {
                        echo 'Step 2'
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
